indices = [
        "Adult mortality rate (probability of dying between 15 and 60 years per 1000 population)",
        "Alcohol, recorded per capita (15+) consumption (in litres of pure alcohol)",
        "Crude suicide rates (per 100 000 population)",
        "Estimate of daily cigarette smoking prevalence (%)",
        "Estimate of daily tobacco smoking prevalence (%)",
        "Estimate of current cigarette smoking prevalence (%)",
        "Estimate of current tobacco smoking prevalence (%)",
        "Estimates of number of homicides",
        "Estimated road traffic death rate (per 100 000 population)",
        "Estimated number of road traffic deaths",
        "Mean BMI (kg/m&#xb2;) (crude estimate)",
        "Mean BMI (kg/m&#xb2;) (age-standardized estimate)",
        "Mean systolic blood pressure (crude estimate)",
        "Mean fasting blood glucose (mmol/l) (crude estimate)",
        "Mean Total Cholesterol (crude estimate)",
        "Mortality rate for 5-14 year-olds (probability of dying per 1000 children aged 5-14 years)",
        "Mortality rate attributed to unintentional poisoning (per 100 000 population)",
        "Number of deaths",
        "Number of infant deaths",
        "Number of under-five deaths",
        "Number of deaths attributed to non-communicable diseases, by type of disease and sex",
        "Prevalence of obesity among adults, BMI &GreaterEqual; 30 (age-standardized estimate) (%)",
        "Prevalence of obesity among children and adolescents, BMI > +2 standard deviations above the median (crude estimate) (%)",
        "Prevalence of overweight among adults, BMI &GreaterEqual; 25 (age-standardized estimate) (%)",
        "Prevalence of overweight among children and adolescents, BMI > +1 standard deviations above the median (crude estimate) (%)",
        "Prevalence of underweight among adults, BMI < 18.5 (age-standardized estimate) (%)",
        "Prevalence of thinness among children and adolescents, BMI < -2 standard deviations below the median (crude estimate) (%)",
    ]
